//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoshipLabelServices
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yurticikargo.com.tr/WSExceptions/")]
    public partial class IT4EMWSException
    {
        
        private string errorCategoryField;
        
        private int errorCodeField;
        
        private string errTextField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCategory
        {
            get
            {
                return this.errorCategoryField;
            }
            set
            {
                this.errorCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errText
        {
            get
            {
                return this.errTextField;
            }
            set
            {
                this.errTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel")]
    public partial class generateLabelResponse
    {
        
        private byte[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel")]
    public partial class generateLabel
    {
        
        private string wsUserNameField;
        
        private string wsPasswordField;
        
        private string wsLangField;
        
        private string applicationTypeField;
        
        private long compIdField;
        
        private long manifestIdField;
        
        private string unitIdField;
        
        private string labelTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string wsUserName
        {
            get
            {
                return this.wsUserNameField;
            }
            set
            {
                this.wsUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wsPassword
        {
            get
            {
                return this.wsPasswordField;
            }
            set
            {
                this.wsPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string wsLang
        {
            get
            {
                return this.wsLangField;
            }
            set
            {
                this.wsLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string applicationType
        {
            get
            {
                return this.applicationTypeField;
            }
            set
            {
                this.applicationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long compId
        {
            get
            {
                return this.compIdField;
            }
            set
            {
                this.compIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long manifestId
        {
            get
            {
                return this.manifestIdField;
            }
            set
            {
                this.manifestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string unitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string labelType
        {
            get
            {
                return this.labelTypeField;
            }
            set
            {
                this.labelTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", ConfigurationName="GeoshipLabelServices.GeoshipLabelServicesImpl")]
    public interface GeoshipLabelServicesImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeoshipLabelServices.IT4EMWSException), Action="", Name="IT4EMWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelResponse1> generateLabelAsync(GeoshipLabelServices.generateLabelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeoshipLabelServices.IT4EMWSException), Action="", Name="IT4EMWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelByPrintLabelParamsResponse> generateLabelByPrintLabelParamsAsync(GeoshipLabelServices.generateLabelByPrintLabelParamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GeoshipLabelServices.IT4EMWSException), Action="", Name="IT4EMWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelExtendedResponse> generateLabelExtendedAsync(GeoshipLabelServices.generateLabelExtendedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLabelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", Order=0)]
        public GeoshipLabelServices.generateLabel generateLabel;
        
        public generateLabelRequest()
        {
        }
        
        public generateLabelRequest(GeoshipLabelServices.generateLabel generateLabel)
        {
            this.generateLabel = generateLabel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLabelResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", Order=0)]
        public GeoshipLabelServices.generateLabelResponse generateLabelResponse;
        
        public generateLabelResponse1()
        {
        }
        
        public generateLabelResponse1(GeoshipLabelServices.generateLabelResponse generateLabelResponse)
        {
            this.generateLabelResponse = generateLabelResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel")]
    public partial class generateLabelByPrintLabelParams
    {
        
        private string wsUserNameField;
        
        private string wsPasswordField;
        
        private string wsLangField;
        
        private string applicationTypeField;
        
        private long compIdField;
        
        private PrintLabelParamsDTO printLabelParamsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string wsUserName
        {
            get
            {
                return this.wsUserNameField;
            }
            set
            {
                this.wsUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wsPassword
        {
            get
            {
                return this.wsPasswordField;
            }
            set
            {
                this.wsPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string wsLang
        {
            get
            {
                return this.wsLangField;
            }
            set
            {
                this.wsLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string applicationType
        {
            get
            {
                return this.applicationTypeField;
            }
            set
            {
                this.applicationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long compId
        {
            get
            {
                return this.compIdField;
            }
            set
            {
                this.compIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public PrintLabelParamsDTO printLabelParams
        {
            get
            {
                return this.printLabelParamsField;
            }
            set
            {
                this.printLabelParamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel")]
    public partial class PrintLabelParamsDTO
    {
        
        private long manifestIdField;
        
        private string unitIdField;
        
        private string pageSizeField;
        
        private string formatField;
        
        private string printDateField;
        
        private string printTimeField;
        
        private string timeZoneField;
        
        private string printReferenceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long manifestId
        {
            get
            {
                return this.manifestIdField;
            }
            set
            {
                this.manifestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string unitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string printDate
        {
            get
            {
                return this.printDateField;
            }
            set
            {
                this.printDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string printTime
        {
            get
            {
                return this.printTimeField;
            }
            set
            {
                this.printTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string timeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string printReferenceData
        {
            get
            {
                return this.printReferenceDataField;
            }
            set
            {
                this.printReferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLabelByPrintLabelParamsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", Order=0)]
        public GeoshipLabelServices.generateLabelByPrintLabelParams generateLabelByPrintLabelParams;
        
        public generateLabelByPrintLabelParamsRequest()
        {
        }
        
        public generateLabelByPrintLabelParamsRequest(GeoshipLabelServices.generateLabelByPrintLabelParams generateLabelByPrintLabelParams)
        {
            this.generateLabelByPrintLabelParams = generateLabelByPrintLabelParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLabelByPrintLabelParamsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateLabelByPrintLabelParamsResponse", Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=false)]
        public byte[][] generateLabelByPrintLabelParamsResponse1;
        
        public generateLabelByPrintLabelParamsResponse()
        {
        }
        
        public generateLabelByPrintLabelParamsResponse(byte[][] generateLabelByPrintLabelParamsResponse1)
        {
            this.generateLabelByPrintLabelParamsResponse1 = generateLabelByPrintLabelParamsResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel")]
    public partial class generateLabelExtended
    {
        
        private string wsUserNameField;
        
        private string wsPasswordField;
        
        private string wsLangField;
        
        private string applicationTypeField;
        
        private long compIdField;
        
        private long manifestIdField;
        
        private string unitIdField;
        
        private string pageSizeField;
        
        private string formatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string wsUserName
        {
            get
            {
                return this.wsUserNameField;
            }
            set
            {
                this.wsUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wsPassword
        {
            get
            {
                return this.wsPasswordField;
            }
            set
            {
                this.wsPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string wsLang
        {
            get
            {
                return this.wsLangField;
            }
            set
            {
                this.wsLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string applicationType
        {
            get
            {
                return this.applicationTypeField;
            }
            set
            {
                this.applicationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long compId
        {
            get
            {
                return this.compIdField;
            }
            set
            {
                this.compIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long manifestId
        {
            get
            {
                return this.manifestIdField;
            }
            set
            {
                this.manifestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string unitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLabelExtendedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", Order=0)]
        public GeoshipLabelServices.generateLabelExtended generateLabelExtended;
        
        public generateLabelExtendedRequest()
        {
        }
        
        public generateLabelExtendedRequest(GeoshipLabelServices.generateLabelExtended generateLabelExtended)
        {
            this.generateLabelExtended = generateLabelExtended;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLabelExtendedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateLabelExtendedResponse", Namespace="http://it4em.yurticikargo.com.tr/geoshipLabel", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=false)]
        public byte[][] generateLabelExtendedResponse1;
        
        public generateLabelExtendedResponse()
        {
        }
        
        public generateLabelExtendedResponse(byte[][] generateLabelExtendedResponse1)
        {
            this.generateLabelExtendedResponse1 = generateLabelExtendedResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface GeoshipLabelServicesImplChannel : GeoshipLabelServices.GeoshipLabelServicesImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class GeoshipLabelServicesImplClient : System.ServiceModel.ClientBase<GeoshipLabelServices.GeoshipLabelServicesImpl>, GeoshipLabelServices.GeoshipLabelServicesImpl
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GeoshipLabelServicesImplClient() : 
                base(GeoshipLabelServicesImplClient.GetDefaultBinding(), GeoshipLabelServicesImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GeoshipLabelServicesImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoshipLabelServicesImplClient(EndpointConfiguration endpointConfiguration) : 
                base(GeoshipLabelServicesImplClient.GetBindingForEndpoint(endpointConfiguration), GeoshipLabelServicesImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoshipLabelServicesImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GeoshipLabelServicesImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoshipLabelServicesImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GeoshipLabelServicesImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GeoshipLabelServicesImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelResponse1> GeoshipLabelServices.GeoshipLabelServicesImpl.generateLabelAsync(GeoshipLabelServices.generateLabelRequest request)
        {
            return base.Channel.generateLabelAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelResponse1> generateLabelAsync(GeoshipLabelServices.generateLabel generateLabel)
        {
            GeoshipLabelServices.generateLabelRequest inValue = new GeoshipLabelServices.generateLabelRequest();
            inValue.generateLabel = generateLabel;
            return ((GeoshipLabelServices.GeoshipLabelServicesImpl)(this)).generateLabelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelByPrintLabelParamsResponse> GeoshipLabelServices.GeoshipLabelServicesImpl.generateLabelByPrintLabelParamsAsync(GeoshipLabelServices.generateLabelByPrintLabelParamsRequest request)
        {
            return base.Channel.generateLabelByPrintLabelParamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelByPrintLabelParamsResponse> generateLabelByPrintLabelParamsAsync(GeoshipLabelServices.generateLabelByPrintLabelParams generateLabelByPrintLabelParams)
        {
            GeoshipLabelServices.generateLabelByPrintLabelParamsRequest inValue = new GeoshipLabelServices.generateLabelByPrintLabelParamsRequest();
            inValue.generateLabelByPrintLabelParams = generateLabelByPrintLabelParams;
            return ((GeoshipLabelServices.GeoshipLabelServicesImpl)(this)).generateLabelByPrintLabelParamsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelExtendedResponse> GeoshipLabelServices.GeoshipLabelServicesImpl.generateLabelExtendedAsync(GeoshipLabelServices.generateLabelExtendedRequest request)
        {
            return base.Channel.generateLabelExtendedAsync(request);
        }
        
        public System.Threading.Tasks.Task<GeoshipLabelServices.generateLabelExtendedResponse> generateLabelExtendedAsync(GeoshipLabelServices.generateLabelExtended generateLabelExtended)
        {
            GeoshipLabelServices.generateLabelExtendedRequest inValue = new GeoshipLabelServices.generateLabelExtendedRequest();
            inValue.generateLabelExtended = generateLabelExtended;
            return ((GeoshipLabelServices.GeoshipLabelServicesImpl)(this)).generateLabelExtendedAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeoshipLabelServicesImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GeoshipLabelServicesImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pprod-geoship.dpsin.dpdgroup.com/IT4EMWebServices/GeoshipLabelServicesImp" +
                        "l");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GeoshipLabelServicesImplClient.GetBindingForEndpoint(EndpointConfiguration.GeoshipLabelServicesImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GeoshipLabelServicesImplClient.GetEndpointAddress(EndpointConfiguration.GeoshipLabelServicesImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            GeoshipLabelServicesImplPort,
        }
    }
}
