//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenCountryCallingCodeServices
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yurticikargo.com.tr/WSExceptions/")]
    public partial class IT4EMWSException
    {
        
        private string errorCategoryField;
        
        private int errorCodeField;
        
        private string errTextField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCategory
        {
            get
            {
                return this.errorCategoryField;
            }
            set
            {
                this.errorCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errText
        {
            get
            {
                return this.errTextField;
            }
            set
            {
                this.errTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/country")]
    public partial class QGenCountryCallingCodeVO
    {
        
        private System.Nullable<long> countryIdField;
        
        private string countryCallingCodeField;
        
        private string codeAlphaField;
        
        private string countryEnglishNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string countryCallingCode
        {
            get
            {
                return this.countryCallingCodeField;
            }
            set
            {
                this.countryCallingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codeAlpha
        {
            get
            {
                return this.codeAlphaField;
            }
            set
            {
                this.codeAlphaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string countryEnglishName
        {
            get
            {
                return this.countryEnglishNameField;
            }
            set
            {
                this.countryEnglishNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/country")]
    public partial class CallingCodeSearchParamsVO
    {
        
        private System.Nullable<long> countryIdField;
        
        private string countryCallingCodeField;
        
        private string codeAlphaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string countryCallingCode
        {
            get
            {
                return this.countryCallingCodeField;
            }
            set
            {
                this.countryCallingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codeAlpha
        {
            get
            {
                return this.codeAlphaField;
            }
            set
            {
                this.codeAlphaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://it4em.yurticikargo.com.tr/country")]
    public partial class getGenCountryCallingCodes
    {
        
        private string wsUserNameField;
        
        private string wsPasswordField;
        
        private string wsLangField;
        
        private string applicationTypeField;
        
        private CallingCodeSearchParamsVO searchParamsVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string wsUserName
        {
            get
            {
                return this.wsUserNameField;
            }
            set
            {
                this.wsUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wsPassword
        {
            get
            {
                return this.wsPasswordField;
            }
            set
            {
                this.wsPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string wsLang
        {
            get
            {
                return this.wsLangField;
            }
            set
            {
                this.wsLangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string applicationType
        {
            get
            {
                return this.applicationTypeField;
            }
            set
            {
                this.applicationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CallingCodeSearchParamsVO searchParamsVO
        {
            get
            {
                return this.searchParamsVOField;
            }
            set
            {
                this.searchParamsVOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://it4em.yurticikargo.com.tr/country", ConfigurationName="GenCountryCallingCodeServices.GenCountryCallingCodeServicesImpl")]
    public interface GenCountryCallingCodeServicesImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GenCountryCallingCodeServices.IT4EMWSException), Action="", Name="IT4EMWSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GenCountryCallingCodeServices.getGenCountryCallingCodesResponse> getGenCountryCallingCodesAsync(GenCountryCallingCodeServices.getGenCountryCallingCodesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGenCountryCallingCodesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://it4em.yurticikargo.com.tr/country", Order=0)]
        public GenCountryCallingCodeServices.getGenCountryCallingCodes getGenCountryCallingCodes;
        
        public getGenCountryCallingCodesRequest()
        {
        }
        
        public getGenCountryCallingCodesRequest(GenCountryCallingCodeServices.getGenCountryCallingCodes getGenCountryCallingCodes)
        {
            this.getGenCountryCallingCodes = getGenCountryCallingCodes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGenCountryCallingCodesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGenCountryCallingCodesResponse", Namespace="http://it4em.yurticikargo.com.tr/country", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenCountryCallingCodeServices.QGenCountryCallingCodeVO[] getGenCountryCallingCodesResponse1;
        
        public getGenCountryCallingCodesResponse()
        {
        }
        
        public getGenCountryCallingCodesResponse(GenCountryCallingCodeServices.QGenCountryCallingCodeVO[] getGenCountryCallingCodesResponse1)
        {
            this.getGenCountryCallingCodesResponse1 = getGenCountryCallingCodesResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface GenCountryCallingCodeServicesImplChannel : GenCountryCallingCodeServices.GenCountryCallingCodeServicesImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class GenCountryCallingCodeServicesImplClient : System.ServiceModel.ClientBase<GenCountryCallingCodeServices.GenCountryCallingCodeServicesImpl>, GenCountryCallingCodeServices.GenCountryCallingCodeServicesImpl
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GenCountryCallingCodeServicesImplClient() : 
                base(GenCountryCallingCodeServicesImplClient.GetDefaultBinding(), GenCountryCallingCodeServicesImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.GenCountryCallingCodeServicesImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenCountryCallingCodeServicesImplClient(EndpointConfiguration endpointConfiguration) : 
                base(GenCountryCallingCodeServicesImplClient.GetBindingForEndpoint(endpointConfiguration), GenCountryCallingCodeServicesImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenCountryCallingCodeServicesImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GenCountryCallingCodeServicesImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenCountryCallingCodeServicesImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GenCountryCallingCodeServicesImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenCountryCallingCodeServicesImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GenCountryCallingCodeServices.getGenCountryCallingCodesResponse> GenCountryCallingCodeServices.GenCountryCallingCodeServicesImpl.getGenCountryCallingCodesAsync(GenCountryCallingCodeServices.getGenCountryCallingCodesRequest request)
        {
            return base.Channel.getGenCountryCallingCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GenCountryCallingCodeServices.getGenCountryCallingCodesResponse> getGenCountryCallingCodesAsync(GenCountryCallingCodeServices.getGenCountryCallingCodes getGenCountryCallingCodes)
        {
            GenCountryCallingCodeServices.getGenCountryCallingCodesRequest inValue = new GenCountryCallingCodeServices.getGenCountryCallingCodesRequest();
            inValue.getGenCountryCallingCodes = getGenCountryCallingCodes;
            return ((GenCountryCallingCodeServices.GenCountryCallingCodeServicesImpl)(this)).getGenCountryCallingCodesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GenCountryCallingCodeServicesImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GenCountryCallingCodeServicesImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pprod-geoship.dpsin.dpdgroup.com/IT4EMWebServices/GenCountryCallingCodeSe" +
                        "rvicesImpl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GenCountryCallingCodeServicesImplClient.GetBindingForEndpoint(EndpointConfiguration.GenCountryCallingCodeServicesImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GenCountryCallingCodeServicesImplClient.GetEndpointAddress(EndpointConfiguration.GenCountryCallingCodeServicesImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            GenCountryCallingCodeServicesImplPort,
        }
    }
}
